[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
hex = "0.4.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple-server-timing-header = "=0.1.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
